import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const root = new URL("../", import.meta.url);
const read = (path) => readFile(new URL(path, root), "utf8");

test("runtime uses bounded futures REST snapshots, no continuous WebSocket", async () => {
  const [worker, gate] = await Promise.all([read("worker/index-clean.ts"), read("lib/gate-market.ts")]);
  assert.match(gate, /\/futures\/usdt\/order_book/);
  assert.match(gate, /with_id=true/);
  assert.match(gate, /\/futures\/usdt\/liq_orders/);
  assert.match(gate, /\/futures\/usdt\/contract_stats/);
  assert.doesNotMatch(gate, /liq_orders\?status=/);
  assert.match(gate, /X-Gate-Size-Decimal/);
  assert.match(gate, /volume_24h_settle/);
  assert.match(gate, /GATE_PUBLIC_TIMEOUT_MS = 2_000/);
  assert.match(gate, /GATE_BULK_TICKER_TIMEOUT_MS = 4_000/);
  assert.match(gate, /gatePublic<GateTicker\[\]>\("\/futures\/usdt\/tickers", GATE_BULK_TICKER_TIMEOUT_MS, 2\)/);
  assert.match(gate, /\/futures\/usdt\/candlesticks/);
  assert.doesNotMatch(worker + gate, /new WebSocket|futures\.order_book_update/);
  assert.match(worker, /MAX_ANCILLARY_CONCURRENCY = 2/);
  assert.match(worker, /plannedTotalDoRequestsPerDay: 50_400/);
  assert.match(worker, /plannedDoWritesPerDay: 54_080/);
  assert.match(worker, /NON_ALARM_WRITE_CAP = 8_000/);
  assert.match(worker, /plannedMaxD1BilledWritesPerDay: 4_800/);
  assert.match(worker, /RADAR_MS = 60_000/);
  assert.match(worker, /await fetchMarketTickers\(\)/);
  assert.match(worker, /stableCandidates/);
  const alarm = worker.slice(worker.indexOf("async alarm("), worker.indexOf("async fetch(request"));
  assert.ok(alarm.indexOf("processBooks") < alarm.indexOf("launchOptionalWork"), "position books must run before optional market work is launched");
  assert.ok(alarm.indexOf("syncLive") < alarm.indexOf("launchOptionalWork"), "LIVE reconciliation must run before optional market work is launched");
  assert.doesNotMatch(alarm, /lastError = `radar:/, "a radar timeout must not become a global execution fault");
  assert.doesNotMatch(alarm, /successes !== this\.runtime\.symbols\.length \? "DEGRADED"/, "partial candidate-book loss must not degrade the whole authority");
  assert.doesNotMatch(alarm, /actionableMarkets === 0 \? `\$\{recoveringMarkets\} realtime markets warming/, "a temporarily empty entry-ready set must not become a global error");
  assert.doesNotMatch(worker, /successes === 0 \? `\$\{this\.runtime\.symbols\.length\} market snapshots unavailable/,
    "a failed staggered subset must never impersonate a full resident-pool outage");
  assert.match(worker, /authorityStale[\s\S]*scheduled market snapshots unavailable; executable freshness expired/);
  assert.match(worker, /completedCandleStrategyCandidate/);
  assert.match(worker, /residentCandleCandidate/);
  assert.doesNotMatch(worker, /alignedFlow: eventAlignedFlow/);
  assert.doesNotMatch(worker, /if \(!radarCandidateExecutionAllowed\(this\.runtime\.radar\.lastScanAt, now\)\) return/);
  assert.match(worker, /maxSubrequestsPerAlarm: 32/);
  assert.match(worker, /now - this\.runtime\.lastStopCheckpointAt < 60_000/);
});

test("only one new DO is bound and all legacy DO storage is explicitly deleted", async () => {
  const config = JSON.parse(await read("wrangler.jsonc"));
  assert.deepEqual(config.durable_objects.bindings, [{ name: "MARKET_STREAM", class_name: "MarketStream" }]);
  const create = config.migrations.at(-2);
  const retire = config.migrations.at(-1);
  assert.deepEqual(create.new_sqlite_classes, ["MarketStream"]);
  assert.equal(create.deleted_classes, undefined);
  for (const name of ["PositionMonitor", "MarketScanner", "LiveTradingCoordinator", "MarketScannerV2", "HTE31MarketScanner", "HTE31TradeManager", "HistoricalArchive"]) assert.ok(retire.deleted_classes.includes(name));
});

test("owner-authenticated live API stays isolated while the strategy arena UI is explicit", async () => {
  const [worker, page, layout, css, live, auth, positionMetrics] = await Promise.all([
    read("worker/index-clean.ts"), read("app/page.tsx"), read("app/layout.tsx"), read("app/globals.css"),
    read("lib/gate-live.ts"), read("lib/owner-auth.ts"), read("lib/position-metrics.ts"),
  ]);
  assert.match(worker, /return handler\.fetch\(request, env, ctx\)/);
  assert.match(worker, /url\.pathname === "\/api\/auth\/login" && request\.method === "POST"/);
  assert.match(worker, /url\.pathname === "\/api\/live\/mode" && request\.method === "POST"/);
  assert.match(worker, /url\.pathname === "\/api\/live\/credentials"/);
  assert.match(worker, /encryptGateCredentials/);
  assert.match(worker, /sameOriginMutation\(request\)/);
  assert.match(worker, /if \(!await ownerAuthenticated\(request, env\)\) return json\(\{ error: "请先登录" \}, 401\)/);
  assert.match(worker, /strategyArena: arenaSummary\(strategyArena\)/);
  assert.match(worker, /requestedEnabled: false, operational: false/);
  assert.match(live, /reduce_only: true/);
  assert.match(live, /credentials\.environment !== "live"/);
  assert.match(auth, /HttpOnly; Secure; SameSite=Strict/);
  assert.match(page, /RUNTIME_REQUEST_TIMEOUT_MS = 12_000/);
  assert.match(page, /RUNTIME_REFRESH_MS = 10_000/);
  assert.match(page, /RUNTIME_RETRY_MS = 3_000/);
  assert.match(page, /window\.addEventListener\("pageshow", resume\)/);
  assert.match(page, /window\.addEventListener\("online", resume\)/);
  assert.match(page, /tabScroll\.current\[tab\] = window\.scrollY/);
  assert.match(page, /viewScroll\.current\[activeView\] = window\.scrollY/);
  assert.match(page, /全境·复利引擎/);
  assert.match(layout, /V12全境·复利引擎 · PAPER/);
  assert.doesNotMatch(layout, /V4自适应影子策略/);
  assert.match(page, /V12 · VERIFIED STATE AUTHORITY/);
  assert.match(page, /转换噪声期没有稳定成本后优势/);
  assert.match(page, /今日净收益/);
  assert.match(page, /实时运行状态/);
  assert.match(page, /策略账户已运行/);
  assert.match(page, /暂停位置/);
  assert.match(page, /下一步准备/);
  assert.match(page, /系统此刻在分析什么/);
  assert.match(page, /为什么分析/);
  assert.match(page, /同类留出胜率/);
  assert.match(page, /不是本单保证/);
  assert.match(page, /后台确认的执行路线/);
  assert.match(page, /const hasRuntimeSnapshot = Boolean\(runtime && arena\)/);
  assert.match(page, /收到真实运行快照后再显示账户、持仓、路线和市场数量/);
  assert.match(page, /收到后台真实快照前不显示“0笔”/);
  assert.match(page, /const showLiveCenter = auth\.authenticated \|\| liveEnabled/);
  assert.match(page, /if \(showLiveCenter\) navigationTabs\.push/);
  assert.match(page, /activeView === "orders"/);
  assert.doesNotMatch(page, /liveEnabled && activeView === "orders"/);
  assert.match(page, /历史实盘记录仍可在“实盘记录”查看/);
  assert.match(page, /function TradeLifecycleRecord/);
  assert.match(page, /function LiveOpenCard/);
  assert.match(page, /function LiveTradeRecord/);
  assert.match(page, /second: "2-digit"/);
  for (const lifecycleLabel of ["进场时间", "出场时间", "持仓时长"]) assert.match(page, new RegExp(lifecycleLabel));
  assert.match(css, /live-trade-history/);
  assert.match(page, /未成交候选/);
  assert.match(page, /auditEvents/);
  assert.doesNotMatch(page, /className="live-off">LIVE OFF/);
  assert.doesNotMatch(page, /手机页面更新延迟|页面摘要延迟|页面数据延迟/);
  assert.doesNotMatch(page, />有效影子</);
  assert.doesNotMatch(page, />观察影子</);
  assert.doesNotMatch(page, /预计成功率/);
  assert.match(page, /当前模拟周期/);
  assert.match(page, /唯一模拟合约账户/);
  assert.match(page, /开启实盘复制/);
  assert.doesNotMatch(page, /双模拟账本|独立策略模拟/);
  assert.doesNotMatch(page, /组合风险预算|目标 \+150 U|双向反应实验 V1|盈利与亏损研究|旧方案归档|账户日志/);
  assert.doesNotMatch(page, /fetch\("\/api\/history|fetch\("\/api\/account-logs/);
  assert.match(page, /所有者登录/);
  assert.match(page, /实盘交易开关/);
  assert.match(page, /撤销系统遗留挂单/);
  assert.match(page, /实盘账户/);
  assert.match(page, /实盘订单/);
  assert.match(page, /API 管理/);
  assert.match(page, /AbortController/);
  assert.match(page, /document\.hidden/);
  assert.match(css, /position:fixed!important/);
  assert.match(css, /strategy-grid/);
  assert.match(positionMetrics, /export function unrealizedPnl/);
  assert.match(positionMetrics, /export function marginReturnRate/);
  assert.doesNotMatch(layout, /requireChatGPTUser|redirect|signin-with-chatgpt/);
  assert.equal(await read("app/chatgpt-auth.ts").then(() => false, () => true), true);
  assert.equal(await read("lib/auth-paths.ts").then(() => false, () => true), true);
});

test("at-least-once alarm and independent feed recovery are explicit", async () => {
  const worker = await read("worker/index-clean.ts");
  assert.match(worker, /lastProcessedSlot/);
  assert.match(worker, /Math\.floor\(now \/ LOOP_MS\)/);
  assert.ok(worker.indexOf("slot <= this.runtime.lastProcessedSlot") < worker.indexOf("setAlarm(prearmed)"));
  assert.match(worker, /\[2_000, 4_000, 8_000, 16_000, 30_000\]/);
  assert.match(worker, /GatePublicError/);
  assert.match(worker, /alarm < Date\.now\(\) - 6_000/);
  assert.ok(worker.indexOf("setAlarm(prearmed)") < worker.indexOf("saveCheckpoint(finishedAt)"));
  assert.match(worker, /this\.processBooks\(now, cycleSymbols\)/);
  assert.doesNotMatch(worker, /this\.processBooks\(slot \* LOOP_MS/);
  assert.match(worker, /usableSnapshot\(snapshot, Math\.max\(now, Date\.now\(\)\)/);
});

test("DO is PAPER authority while D1 is a bounded outbox mirror", async () => {
  const worker = await read("worker/index-clean.ts");
  assert.doesNotMatch(worker, /loadEquity|hydrateOpenPositions/);
  assert.match(worker, /if \(criticalChanged \|\| openedThisCycle\)/);
  assert.ok(worker.indexOf("saveCheckpoint(now, true)") < worker.indexOf("await this.drainOutbox(now)"));
  assert.match(worker, /const books = await this\.processBooks\(now, cycleSymbols\)/);
  assert.ok(worker.indexOf("this.publishCriticalHealth(Date.now(), books)") < worker.indexOf("this.launchOptionalWork(now, universeDue)"));
  assert.doesNotMatch(worker.slice(worker.indexOf("async alarm("), worker.indexOf("async fetch(request")), /await this\.launchOptionalWork/);
  assert.match(worker, /this\.ctx\.waitUntil\(tracked\)/);
  assert.match(worker, /runtimeCache.*expiresAt/s);
  assert.match(worker, /this\.runtime\.d1Writes \+ billedWrites > 4_800/);
  assert.doesNotMatch(worker, /review-entry:|review-exit:/);
  assert.match(worker, /ORDER_CLOSE_DIAGNOSTIC/);
  assert.match(worker, /FROM paper_events WHERE event_type='PAPER_BANKRUPTCY'/);
  assert.match(worker, /event_type='ORDER_CLOSE_DIAGNOSTIC'[\s\S]*observed_at>=\? AND observed_at<=\?/);
  assert.match(worker, /completeTrades\.length > item\.report\.trades\.length/);
});

test("V12 verified-route engine is causal, selective, cost-aware, and the sole LIVE order source", async () => {
  const [arena, allRegime, regime, gateLive, worker, page, migration, coveragePolicy] = await Promise.all([
    read("lib/strategy-arena.ts"), read("lib/all-regime-engine.ts"), read("lib/market-regime.ts"),
    read("lib/gate-live.ts"), read("worker/index-clean.ts"), read("app/page.tsx"),
    read("drizzle/0035_strategy_arena_fresh_start.sql"),
    read("lib/strategy-coverage-policy.ts"),
  ]);
  assert.match(arena, /STRATEGY_CATALOG/);
  assert.match(arena, /STRATEGY_ARENA_VERSION = 12/);
  assert.match(allRegime, /ALL_REGIME_SYSTEM_NAME = "全境·复利引擎"/);
  for (const name of ["势承", "潮补", "静移", "冲衡", "脉折", "潮接"]) assert.match(allRegime, new RegExp(name));
  assert.match(allRegime, /detectAllRegimeRoutes/);
  assert.doesNotMatch(arena, /adaptiveMechanismForPlaybook/);
  assert.match(arena, /ARENA_FRICTION_RATE = 0\.0014/);
  assert.match(arena, /ARENA_MAX_COST_SHARE = 0\.25/);
  assert.match(arena, /PORTFOLIO_REALTIME_CAPACITY = 10/);
  assert.match(arena, /recentObservations/);
  assert.match(arena, /currentRouteChecks/);
  assert.match(arena, /cutoverPending/);
  assert.match(arena, /sizePaperPosition/);
  assert.match(arena, /selectSafeLeverage/);
  assert.match(arena, /contracts/);
  assert.match(arena, /quantoMultiplier/);
  assert.match(arena, /ARENA_MAX_OPEN = 240/);
  assert.match(arena, /ARENA_HISTORY_LIMIT = 240/);
  assert.match(arena, /PORTFOLIO_TRADE_RISK_TARGET_USDT = 10/);
  assert.doesNotMatch(arena, /EMPIRICAL_COST/);
  assert.match(arena, /seenSignals\.length > 2_000/);
  assert.match(regime, /MARKET_REGIME_MIN_SAMPLES = 18/);
  assert.match(regime, /selectDiverseMarketPool/);
  assert.doesNotMatch(arena, /fetch\(|DB\.prepare|D1Database|GateLiveClient|reconcilePaper/);
  assert.match(worker, /const decision: Decision \| null = null/);
  assert.match(worker, /cycleBookSymbols/);
  assert.match(worker, /approvedRouteScore/);
  assert.match(worker, /feedQuality/);
  assert.match(worker, /allowOpen: false/);
  assert.match(worker, /observeStrategyArena/);
  assert.match(worker, /advanceStrategyArena/);
  assert.match(worker, /desiredPortfolio = this\.runtime\.strategyArena\.portfolioOpen/);
  assert.match(worker, /eligibleForLiveMirror/);
  assert.match(worker, /position\.currentStop = arenaProtectionStop\(selectedTrade\)/);
  assert.match(worker, /mirrorNotionalFraction: trade\.notional \/ Math\.max\(trade\.accountEquityAtOpen/);
  assert.match(worker, /strategyArena: normalizeStrategyArena\(saved\.strategyArena\)/);
  assert.match(worker, /resetStrategyArenaAccount/);
  assert.match(worker, /minimumPortfolioRiskUsdt: 0/);
  assert.match(worker, /targetPortfolioRiskUsdt: PORTFOLIO_TRADE_RISK_TARGET_USDT/);
  assert.match(worker, /empiricalCostFloorRate: ARENA_FRICTION_RATE/);
  assert.match(arena, /POLARITY_STREAK = 3/);
  assert.match(arena, /reversed\.every\(\(row\) => row\.netReturnRate > 0\)/);
  assert.match(arena, /profitArmIsExit: false/);
  assert.doesNotMatch(arena, /Object\.keys\(state\.portfolioOpen\)\.length >= MAX_PORTFOLIO_POSITIONS/);
  assert.doesNotMatch(arena, /globalOpportunityRank \?\? 1\) > MAX_PORTFOLIO_POSITIONS/);
  assert.match(arena, /RUNNER_EXIT/);
  assert.match(page, /盈利启动后只抬保护，不封顶/);
  assert.match(arena, /cloneShadowForPortfolio/);
  assert.match(arena, /paperEvaluation: true/);
  assert.match(arena, /extremeSequenceAuthority: false/);
  assert.match(arena, /generatedRouteAuthority: false/);
  assert.match(arena, /legacyStrategyAuthority: false/);
  assert.match(coveragePolicy, /TRANSITION: "WAIT"/);
  assert.match(coveragePolicy, /ORDERLY_TREND:BROAD_DOWN:HIGH_EDGE/);
  assert.doesNotMatch(page, />观察影子</);
  assert.match(page, /当前模拟周期/);
  assert.match(page, /历史归档/);
  assert.match(page, /const \[archiveOpen, setArchiveOpen\] = useState\(false\)/);
  assert.match(page, /className="archive-toggle" type="button" aria-expanded=\{archiveOpen\}/);
  assert.match(page, /\{archiveOpen && <div className="archive-content">/);
  assert.match(page, /查看归档 ›/);
  assert.match(page, /runtimeBackendOperational\(runtime\)/);
  assert.match(page, /RUNTIME_RETRY_MS = 3_000/);
  assert.doesNotMatch(page, /页面摘要延迟，交易后台继续独立运行/);
  assert.doesNotMatch(arena, /state\.portfolioEquity \* 0\.5/);
  assert.match(arena, /state\.portfolioEquity \* MAX_NOTIONAL_TO_EQUITY/);
  assert.match(arena, /state\.portfolioEquity \* MIN_PORTFOLIO_NOTIONAL_TO_EQUITY/);
  assert.match(arena, /MEANINGFUL_SIZE/);
  assert.match(gateLive, /Math\.min\(MAX_NOTIONAL_TO_EQUITY, input\.mirrorNotionalFraction\)/);
  assert.match(worker, /maxNotionalMultiple: MAX_NOTIONAL_TO_EQUITY/);
  assert.match(worker, /buildLiveStopIntent\(position, tick\)/);
  assert.match(gateLive, /side === "LONG" \? Math\.floor\(units \+ 1e-9\) : Math\.ceil\(units - 1e-9\)/);
  assert.match(page, /重置1000 U模拟资金/);
  assert.match(page, /confirm: "RESET_PAPER"/);
  assert.match(worker, /SCAN_UNIVERSE_SIZE = 30/);
  assert.match(worker, /maxOpenPositions: null/);
  assert.match(migration, /DELETE FROM `paper_events`/);
  assert.match(migration, /DELETE FROM `paper_positions`/);
  assert.match(migration, /DELETE FROM `paper_plans`/);
  assert.doesNotMatch(migration, /live_exchange_credentials/);
});

test("Gate degradation is endpoint-aware, incremental, and only blocking after retained paths expire", async () => {
  const [gate, worker, page] = await Promise.all([
    read("lib/gate-market.ts"), read("worker/index-clean.ts"), read("app/page.tsx"),
  ]);
  assert.match(gate, /https:\/\/fx-api\.gateio\.ws\/api\/v4/);
  assert.match(gate, /endpointBackoffUntil/);
  assert.match(gate, /x-gate-ratelimit-reset-timestamp/);
  assert.match(worker, /const RADAR_MS = 60_000/);
  assert.match(worker, /prior\.length >= 100 \? 4 : 120/);
  assert.match(worker, /mergeStrategyCandlePath/);
  assert.match(worker, /STRATEGY_CANDLE_STALE_MS = 11 \* 60_000/);
  assert.match(page, /路径短错 \{degradedPathMarkets\}（有效快照保留）/);
  assert.doesNotMatch(gate, /apiSecret|apiKey|KEY|SIGN/);
});

test("legacy sizing and portfolio mirroring both retain bounded account risk", async () => {
  const [core, live] = await Promise.all([read("lib/liquidity-core.ts"), read("lib/gate-live.ts")]);
  assert.match(core, /MIN_SINGLE_TRADE_RISK_RATE = 0\.01/);
  assert.match(core, /MAX_SINGLE_TRADE_RISK_RATE = 0\.02/);
  assert.match(core, /PORTFOLIO_RISK_CAP = 0\.10/);
  assert.match(core, /CORRELATED_DIRECTION_RISK_CAP = 0\.065/);
  assert.match(core, /DYNAMIC_PROTECTION_MIN_CONFIRMED_R = 1\.5/);
  assert.match(core, /DYNAMIC_PROTECTION_MIN_TARGET_PROGRESS = 0\.70/);
  assert.match(core, /MAX_NOTIONAL_TO_EQUITY = 4/);
  assert.match(core, /MIN_NET_TARGET_RETURN_ON_EQUITY = 0\.002/);
  assert.match(core, /Math\.min\(riskSizedNotional, input\.equity \* MAX_NOTIONAL_TO_EQUITY\)/);
  assert.match(live, /sizePaperPosition\(/);
  assert.match(live, /tradeEconomics\(/);
  assert.match(live, /mirrorNotionalFraction/);
});

test("cutover is credential-bound and removes legacy DOs only after v11 health", async () => {
  const workflow = await read(".github/workflows/sentinel-v2-ci.yml");
  assert.equal((workflow.match(/\.runtime\.strategyArena\.version == 12/g) ?? []).length, 2);
  assert.equal((workflow.match(/grep -Fq '全境·复利引擎'/g) ?? []).length, 2);
  assert.match(workflow, /Require crypto-only full-phase candidate coverage/);
  assert.ok(workflow.indexOf("research:all-regime") < workflow.indexOf("research:v12"));
  assert.doesNotMatch(workflow, /run: npm run research:v11/);
  assert.match(workflow, /id,exchange,environment,ciphertext,iv,crypto_version,key_hint,gate_user_id,owner_account_id,permission_summary_json,status,last_verified_at,last_error,created_at,updated_at/);
  assert.match(workflow, /index\.prepare\.js/);
  assert.match(workflow, /class RetiredDurableObject extends DurableObject/);
  assert.ok(workflow.indexOf("index.prepare.js") < workflow.indexOf("Deploy v6 prepare config"));
  assert.match(workflow, /for attempt in 1 2 3 4 5/);
  assert.match(workflow, /valid non-zero inventory result is authoritative/);
  assert.match(workflow, /wrangler\.compat-preflight\.json/);
  assert.match(workflow, /index\.cutover-preview\.js/);
  assert.match(workflow, /export class MarketStream extends DurableObject/);
  assert.match(workflow, /WORKER_BASE_URL\/api\/live\/preflight/);
  assert.match(workflow, /\.durable_objects == null/);
  assert.match(workflow, /tag: "v6-liquidity-three-state"/);
  assert.equal((workflow.match(/rules: \.rules/g) ?? []).length, 1);
  assert.doesNotMatch(workflow, /versions upload|CUTOVER_AUDIT_PREVIEW|CUTOVER_PREFLIGHT_URL/);
  assert.ok(workflow.indexOf("wrangler.compat-preflight.json") < workflow.indexOf("Require two fresh read-only Gate"));
  assert.ok(workflow.indexOf("Require two fresh read-only Gate") < workflow.indexOf("Deploy v6 prepare config"));
  assert.match(workflow, /phase" == "audit"/);
  assert.doesNotMatch(workflow, /Generate masked TTL token and deploy trusted read-only preflight/);
  assert.ok(workflow.indexOf("wrangler.prepare.json") < workflow.indexOf("Deploy reviewed final v7"));
  assert.ok(workflow.indexOf("Require continuously advancing v6 health") < workflow.indexOf("Deploy reviewed final v7"));
  assert.ok(workflow.indexOf("Recheck Gate twice") < workflow.indexOf("Deploy reviewed final v7"));
  assert.ok(workflow.indexOf("Deploy reviewed final v7") < workflow.indexOf("0033 D1 purge last"));
  assert.match(workflow, /tables_csv/);
});

test("ordinary production deploy accepts evolved paper equity", async () => {
  const workflow = await read(".github/workflows/sentinel-v2-ci.yml");
  const ordinaryDeploy = workflow.slice(workflow.lastIndexOf("- name: Verify advancing production health"));
  assert.match(ordinaryDeploy, /\(\.runtime\.strategyArena\.portfolioEquity \| type\) == "number"/);
  assert.match(ordinaryDeploy, /\.runtime\.strategyArena\.portfolioEquity > 0/);
  assert.doesNotMatch(ordinaryDeploy, /portfolioEquity == 1000/);
});
