import assert from "node:assert/strict";
import test from "node:test";
import { buildSentinelV2MarketContext } from "../lib/sentinel-v2-core.ts";
import { evaluateSentinelV2Strategies, strategy2ExperienceKey } from "../lib/sentinel-v2-strategy.ts";
import type { Strategy2Input } from "../lib/strategy-2-engine.ts";
import type { UniverseTicker } from "../lib/gate-client.ts";
import type { Candle } from "../lib/signal-engine.ts";

const observedAt=Date.UTC(2026,7,26,5,0,0);
function universe(changes:number[]):UniverseTicker[]{return changes.map((changePercentage,i)=>({symbol:`C${i+10}_USDT`,price:100+i,changePercentage,volumeUsd:100_000_000,fundingRate:.0001,basisPct:0,coarseScore:Math.max(-1,Math.min(1,changePercentage/7)),confidence:60,state:"observing",stateLabel:"持续观察",side:"WAIT"}))}
function candles(count=90):Candle[]{const rows:Candle[]=[];for(let i=0;i<count;i++){const close=100+i*.05+Math.sin(i/4)*.06;const open=close-.02;rows.push({time:Math.floor((observedAt-(count-i)*300_000)/1000),open,high:Math.max(open,close)+.1,low:Math.min(open,close)-.1,close,volume:1000+(i%5)*50})}return rows}
function dennisCandles():Candle[]{const rows=candles();const priorHigh=Math.max(...rows.slice(-23,-2).map(c=>c.high));const last=rows.at(-1)!;rows[rows.length-1]={...last,open:priorHigh+.02,low:priorHigh-.06,close:priorHigh+.28,high:priorHigh+.34,volume:2200};return rows}
function input(patch:Partial<Strategy2Input>={}):Strategy2Input{return {symbol:"SOL_USDT",observedAt,futuresPrice:104.4,volumeUsd:800_000_000,changePercentage:6.4,fundingRate:.0001,openInterestChangePct:1.5,spotCvdRatio:.08,orderBookImbalance:.1,liquidationImbalance:.05,multiTimeframeTrend:.75,benchmarkMomentum:1.1,macroEventRisk:.1,dataQuality:.95,candles5m:dennisCandles(),crossSectionRank:.96,rotationVelocity:.06,marketAdvancingRatio:.5,marketDecliningRatio:.5,...patch}}

test("Human Trader Engine production authority exposes exactly three independent traders",()=>{const market=buildSentinelV2MarketContext({observedAt,universe:universe([3,2.7,2.5,2.2,2,1.8,1.5,1.2,1,.8,.5,.3]),benchmarkMomentum:2.8,optionsIvPercentile:.45,macroEventRisk:.1});const rows=dennisCandles();const result=evaluateSentinelV2Strategies(input({candles5m:rows,futuresPrice:rows.at(-1)!.close}),{market,openTrades:[],experienceBook:{}});assert.equal(result.opportunities.length,3);assert.equal(result.signals.length,3);assert.deepEqual(result.opportunities.map(o=>o.playbook),["HT1_DENNIS_TREND","HT2_RASCHKE_PULLBACK","HT3_TURTLE_SOUP"]);assert.ok(result.opportunities.every(o=>o.supportingPlaybooks.length===0&&o.strategyConflict===0));});

test("entry authority comes from the trader setup, not a universal opportunity-score threshold",()=>{const market=buildSentinelV2MarketContext({observedAt,universe:universe([3.2,2.9,2.7,2.5,2.2,2,1.8,1.5,1.2,1,.8,.6]),benchmarkMomentum:2.5,optionsIvPercentile:.4,macroEventRisk:.1});const rows=dennisCandles();const result=evaluateSentinelV2Strategies(input({candles5m:rows,futuresPrice:rows.at(-1)!.close}),{market,openTrades:[],experienceBook:{}});const dennis=result.opportunities.find(o=>o.playbook==="HT1_DENNIS_TREND");assert.ok(dennis);assert.equal(dennis!.state,"TRADE");assert.equal(result.opportunities.filter(o=>o.state==="TRADE").length,1);assert.ok(result.signals.find(s=>s.strategyMeta.playbookId==="HT1_DENNIS_TREND")?.entryPlan?.checks.some(c=>c.key==="dennis-breakout"&&c.required&&c.passed));});

test("global RED remains a hard safety stop without turning neutral global regimes into direction votes",()=>{const market=buildSentinelV2MarketContext({observedAt,universe:universe([.4,.2,.1,0,-.1,-.2,.3,-.3,.2,-.2,.1,-.1]),benchmarkMomentum:.1,optionsIvPercentile:.35,macroEventRisk:.99});const rows=dennisCandles();const result=evaluateSentinelV2Strategies(input({candles5m:rows,futuresPrice:rows.at(-1)!.close,macroEventRisk:.99}),{market,openTrades:[],experienceBook:{}});assert.ok(result.opportunities.every(o=>o.state!=="TRADE"));assert.ok(result.opportunities.some(o=>o.rejectReasons.includes("GLOBAL_RISK_RED")||o.rejectReasons.includes("EMERGENCY_EVENT_RISK")));});

test("new HT learning cells start clean and a proven negative edge hard-rejects only that trader/environment",()=>{const market=buildSentinelV2MarketContext({observedAt,universe:universe([3.2,2.9,2.7,2.5,2.2,2,1.8,1.5,1.2,1,.8,.6]),benchmarkMomentum:2.5,optionsIvPercentile:.4,macroEventRisk:.1});const rows=dennisCandles();const base=evaluateSentinelV2Strategies(input({candles5m:rows,futuresPrice:rows.at(-1)!.close}),{market,openTrades:[],experienceBook:{}});const candidate=base.opportunities.find(o=>o.state==="TRADE"&&o.side!=="WAIT");assert.ok(candidate);assert.equal(candidate!.experienceSamples,0);const key=strategy2ExperienceKey(candidate!.playbook,candidate!.globalRegime,candidate!.assetRegime,candidate!.side as "LONG"|"SHORT");const learned=evaluateSentinelV2Strategies(input({candles5m:rows,futuresPrice:rows.at(-1)!.close}),{market,openTrades:[],experienceBook:{[key]:{sampleCount:14,wins:1,losses:13,winRate:1/14,expectancyR:-.72,averageNetPct:-.6,posteriorExpectancyR:-.72,recentExpectancyR:-.85,effectiveSampleCount:11.5,t1HitRate:.08,directionFailureRate:.79,inverseT1PotentialRate:.71,edgeLowerBoundR:-.95,edgeUpperBoundR:-.49,edgeConfidence:88,edgeState:"negative",driftR:-.13,forwardSampleCount:8,forwardExpectancyR:-.81,forwardInverseT1PotentialRate:.75}}});const rejected=learned.opportunities.find(o=>o.playbook===candidate!.playbook);assert.ok(rejected);assert.equal(rejected!.state,"REJECT");assert.equal(rejected!.riskMultiplier,0);assert.ok(rejected!.rejectReasons.includes("LEARNED_EDGE_NEGATIVE"));});
