import type {ShadowCapsule} from './shadow-inverse-ledger.ts';
import type {ReactionArea} from './winner-policy.ts';
import type {ReturnLogic} from './direct-strategy-types.ts';
import type {InverseCopy} from './shadow-inverse-ledger.ts';

export const UNIFIED_EXECUTION_VERSION='return-continuation-v1';
export type UnifiedBranch='RETURN'|'CONTINUATION';
export type Acceptance={side:'LONG'|'SHORT';at:number;bars:number[];path:'HOLD_OUTSIDE'|'RETEST_RESTART';stop:number;boundary:number;epsilon:number};
export type UnifiedTrade={version:typeof UNIFIED_EXECUTION_VERSION|'dual-thesis-v2';branch:UnifiedBranch;sourceId:string;referenceId:string;
  marketRoute?:import('./market-authority.ts').MarketRoute;
  adaptive?:import('./adaptive-controller.ts').AdaptiveHolding;
  response?:import('./event-response.ts').ResponseHolding;
  returnLogic?:ReturnLogic;migratedAt?:number;legacyReceipt?:InverseCopy;
  researchObservation?:{checkedAt:number;confirmation:Acceptance|null;flowConfirmed:boolean};
  entryReason:string;holdReason:string;exitCondition:string;lastDecisionAt:number;lastBarAt:number;
  region:ReactionArea|null;epsilon:number;confirmation:Acceptance|null;initialStop:number|null;
  referenceContracts:number;referenceClosedAt?:number;referenceExitReason?:string|null;
  predecessorId?:string;predecessorNet?:number;decision:'HOLD'|'REVIEW'|'EXIT';
  explanationEvents:{at:number;kind:'ENTRY'|'CONFIRM'|'REDUCE'|'EXIT';reason:string;price:number;quoteAt:number}[];
};
export type UnifiedEpisode={sourceId:string;symbol:string;createdAt:number;region:ReactionArea|null;epsilon:number;
  handled:boolean;converted:boolean;ended:boolean;confirmation:Acceptance|null;continuationSeen?:boolean;lastBarAt:number;reason:string};
export type UnifiedExecution={version:typeof UNIFIED_EXECUTION_VERSION;cutoverAt:number;reference:ShadowCapsule;
  episodes:Record<string,UnifiedEpisode>;legacyIds:string[];completedConversions:number;droppedEpisodes:number};
