import { index, integer, primaryKey, real, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const hte31Trades = sqliteTable("hte31_trades", {
  id: text("id").primaryKey(),
  activeKey: text("active_key").unique(),
  symbol: text("symbol").notNull(),
  status: text("status", { enum: ["holding", "closed"] }).notNull().default("holding"),
  traderId: text("trader_id", { enum: [
    "dennis_trend", "raschke_pullback", "turtle_soup", "exhaustion_reversal", "higher_timeframe_swing",
    "dennis_trend_v2", "raschke_pullback_v2", "turtle_soup_v2", "higher_timeframe_swing_v2",
    "range_rotation", "compression_expansion", "relative_strength", "momentum_continuation",
    "direct_market_brain",
  ] }).notNull(),
  setupId: text("setup_id").notNull(),
  decisionAuthority: text("decision_authority").notNull().default("legacy_hte31"),
  brainVersion: text("brain_version"),
  decisionSnapshotJson: text("decision_snapshot_json").notNull().default("{}"),
  independentEventKey: text("independent_event_key"),
  side: text("side", { enum: ["LONG", "SHORT"] }).notNull(),
  assetRegime: text("asset_regime").notNull(),
  confidence: integer("confidence").notNull(),
  entryAt: integer("entry_at").notNull(),
  entryPrice: real("entry_price").notNull(),
  initialStopPrice: real("initial_stop_price").notNull(),
  currentStopPrice: real("current_stop_price").notNull(),
  takeProfit1Price: real("take_profit_1_price").notNull(),
  takeProfit2Price: real("take_profit_2_price").notNull(),
  target1HitAt: integer("target_1_hit_at"),
  maxHoldingMinutes: integer("max_holding_minutes").notNull(),
  riskReward: real("risk_reward").notNull(),
  riskBudgetUsdt: real("risk_budget_usdt").notNull(),
  notionalUsdt: real("notional_usdt").notNull(),
  marginUsdt: real("margin_usdt").notNull(),
  quantity: real("quantity").notNull(),
  leverage: integer("leverage").notNull(),
  entryTrigger: text("entry_trigger").notNull(),
  entryThesis: text("entry_thesis").notNull(),
  entryChecksJson: text("entry_checks_json").notNull().default("[]"),
  entryMetricsJson: text("entry_metrics_json").notNull().default("[]"),
  lastPrice: real("last_price").notNull(),
  lastEvaluatedAt: integer("last_evaluated_at").notNull(),
  maxPriceSeen: real("max_price_seen").notNull(),
  minPriceSeen: real("min_price_seen").notNull(),
  unrealizedNetPct: real("unrealized_net_pct").notNull().default(0),
  unrealizedNetUsdt: real("unrealized_net_usdt").notNull().default(0),
  progressR: real("progress_r").notNull().default(0),
  exitAt: integer("exit_at"),
  exitPrice: real("exit_price"),
  exitCode: text("exit_code"),
  exitReason: text("exit_reason"),
  grossMovePct: real("gross_move_pct"),
  netMovePct: real("net_move_pct"),
  grossPnlUsdt: real("gross_pnl_usdt"),
  costUsdt: real("cost_usdt"),
  netPnlUsdt: real("net_pnl_usdt"),
  mfePct: real("mfe_pct"),
  maePct: real("mae_pct"),
  holdMinutes: real("hold_minutes"),
  postExitStatus: text("post_exit_status", { enum: ["pending", "observing", "complete"] }).notNull().default("pending"),
  postExitMfePct: real("post_exit_mfe_pct"),
  postExitMaePct: real("post_exit_mae_pct"),
  exitCapturePct: real("exit_capture_pct"),
  exitEfficiency: real("exit_efficiency"),
  stopRecovery: integer("stop_recovery", { mode: "boolean" }),
  postExitLabel: text("post_exit_label"),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
}, (table) => [
  index("hte31_trades_status_time_idx").on(table.status, table.entryAt),
  index("hte31_trades_trader_exit_idx").on(table.traderId, table.exitAt),
  index("hte31_trades_symbol_time_idx").on(table.symbol, table.entryAt),
]);

export const hte31SimulationEpochs = sqliteTable("hte31_simulation_epochs", {
  id: text("id").primaryKey(),
  startedAt: integer("started_at").notNull(),
  startingCapitalUsdt: real("starting_capital_usdt").notNull(),
  createdAt: integer("created_at").notNull(),
}, (table) => [
  index("hte31_simulation_epochs_started_idx").on(table.startedAt),
]);

export const hte31PaperResetState = sqliteTable("hte31_paper_reset_state", {
  id: text("id").primaryKey(),
  status: text("status", { enum: ["pending", "completed"] }).notNull(),
  resetMode: text("reset_mode", { enum: ["natural", "force_archive"] }).notNull().default("natural"),
  requestedCapitalUsdt: real("requested_capital_usdt").notNull(),
  requestedAt: integer("requested_at").notNull(),
  completedAt: integer("completed_at"),
  updatedAt: integer("updated_at").notNull(),
});

export const hte31Evaluations = sqliteTable("hte31_evaluations", {
  id: text("id").primaryKey(),
  symbol: text("symbol").notNull(),
  observedAt: integer("observed_at").notNull(),
  traderId: text("trader_id", { enum: [
    "dennis_trend", "raschke_pullback", "turtle_soup", "exhaustion_reversal", "higher_timeframe_swing",
    "dennis_trend_v2", "raschke_pullback_v2", "turtle_soup_v2", "higher_timeframe_swing_v2",
    "range_rotation", "compression_expansion", "relative_strength", "momentum_continuation",
    "direct_market_brain",
  ] }).notNull(),
  setupId: text("setup_id").notNull(),
  state: text("state", { enum: ["ready", "watching", "blocked"] }).notNull(),
  side: text("side", { enum: ["LONG", "SHORT", "WAIT"] }).notNull(),
  confidence: integer("confidence").notNull(),
  setupScore: real("setup_score").notNull(),
  evidenceScore: real("evidence_score").notNull(),
  assetRegime: text("asset_regime").notNull(),
  thesis: text("thesis").notNull(),
  reasonsJson: text("reasons_json").notNull().default("[]"),
  blockersJson: text("blockers_json").notNull().default("[]"),
  entryPlanJson: text("entry_plan_json").notNull().default("null"),
}, (table) => [
  index("hte31_eval_time_idx").on(table.observedAt),
  index("hte31_eval_symbol_time_idx").on(table.symbol, table.observedAt),
  index("hte31_eval_trader_time_idx").on(table.traderId, table.observedAt),
]);

export const hte31Learning = sqliteTable("hte31_learning", {
  id: text("id").primaryKey(),
  traderId: text("trader_id", { enum: [
    "dennis_trend", "raschke_pullback", "turtle_soup", "exhaustion_reversal", "higher_timeframe_swing",
    "dennis_trend_v2", "raschke_pullback_v2", "turtle_soup_v2", "higher_timeframe_swing_v2",
    "range_rotation", "compression_expansion", "relative_strength", "momentum_continuation",
    "direct_market_brain",
  ] }).notNull(),
  assetRegime: text("asset_regime").notNull(),
  side: text("side", { enum: ["LONG", "SHORT"] }).notNull(),
  sampleCount: integer("sample_count").notNull().default(0),
  wins: integer("wins").notNull().default(0),
  losses: integer("losses").notNull().default(0),
  expectancyR: real("expectancy_r").notNull().default(0),
  grossProfitR: real("gross_profit_r").notNull().default(0),
  grossLossR: real("gross_loss_r").notNull().default(0),
  averageMfeR: real("average_mfe_r").notNull().default(0),
  averageMaeR: real("average_mae_r").notNull().default(0),
  averageExitEfficiency: real("average_exit_efficiency").notNull().default(0),
  updatedAt: integer("updated_at").notNull(),
}, (table) => [
  index("hte31_learning_trader_idx").on(table.traderId, table.updatedAt),
]);

export const hte31TradeCharts = sqliteTable("hte31_trade_charts", {
  tradeId: text("trade_id").primaryKey(),
  symbol: text("symbol").notNull(),
  entryCandlesJson: text("entry_candles_json").notNull().default("[]"),
  holdingCandlesJson: text("holding_candles_json").notNull().default("[]"),
  postExitCandlesJson: text("post_exit_candles_json").notNull().default("[]"),
  entryQualityJson: text("entry_quality_json").notNull().default("null"),
  updatedAt: integer("updated_at").notNull(),
});

export const hte31PostExitObservations = sqliteTable("hte31_post_exit_observations", {
  tradeId: text("trade_id").notNull(),
  horizonMinutes: integer("horizon_minutes").notNull(),
  dueAt: integer("due_at").notNull(),
  observedAt: integer("observed_at"),
  status: text("status", { enum: ["pending", "complete"] }).notNull().default("pending"),
  qualityStatus: text("quality_status", { enum: ["PENDING", "READY", "STALE", "UNAVAILABLE"] }).notNull().default("PENDING"),
  coveragePct: real("coverage_pct"),
  lastError: text("last_error"),
  retryCount: integer("retry_count").notNull().default(0),
  nextRetryAt: integer("next_retry_at"),
  price: real("price"),
  favorablePct: real("favorable_pct"),
  adversePct: real("adverse_pct"),
  favorableR: real("favorable_r"),
  adverseR: real("adverse_r"),
  candlesJson: text("candles_json").notNull().default("[]"),
}, (table) => [
  primaryKey({ columns: [table.tradeId, table.horizonMinutes] }),
  index("hte31_post_exit_due_idx").on(table.status, table.dueAt),
]);
