import { sql } from "drizzle-orm";
import { index, integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const userAccounts = sqliteTable("user_accounts", {
  id: text("id").primaryKey(),
  email: text("email").notNull().unique(),
  displayName: text("display_name").notNull(),
  role: text("role", { enum: ["owner", "member"] }).notNull().default("member"),
  status: text("status", { enum: ["active", "disabled"] }).notNull().default("active"),
  createdAt: integer("created_at").notNull(),
  lastSeenAt: integer("last_seen_at").notNull(),
}, (table) => [
  index("user_accounts_status_idx").on(table.status),
  index("user_accounts_last_seen_idx").on(table.lastSeenAt),
]);

export const alertEvents = sqliteTable("alert_events", {
  id: text("id").primaryKey(),
  fingerprint: text("fingerprint").notNull().unique(),
  tradeId: text("trade_id"),
  symbol: text("symbol").notNull(),
  state: text("state", { enum: ["observing", "pre_alert", "confirmed", "blocked", "invalidated"] }).notNull(),
  side: text("side", { enum: ["LONG", "SHORT", "WAIT"] }).notNull(),
  confidence: integer("confidence").notNull(),
  directionalScore: real("directional_score").notNull(),
  posteriorLong: real("posterior_long"),
  dataQuality: real("data_quality").notNull(),
  regime: text("regime").notNull(),
  observedAt: integer("observed_at").notNull(),
  expiresAt: integer("expires_at").notNull(),
  entryPrice: real("entry_price"),
  entryLow: real("entry_low"),
  entryHigh: real("entry_high"),
  invalidationPrice: real("invalidation_price"),
  trigger: text("trigger").notNull(),
  thesis: text("thesis").notNull(),
  evidenceJson: text("evidence_json").notNull().default("[]"),
  counterEvidenceJson: text("counter_evidence_json").notNull().default("[]"),
  metricsJson: text("metrics_json").notNull().default("[]"),
  sourceSnapshotJson: text("source_snapshot_json").notNull().default("{}"),
  outcomeState: text("outcome_state", { enum: ["open", "invalidated", "expired", "favorable", "unfavorable"] }).notNull().default("open"),
  outcomeAt: integer("outcome_at"),
  exitPrice: real("exit_price"),
  maxPriceSeen: real("max_price_seen"),
  minPriceSeen: real("min_price_seen"),
  grossMovePct: real("gross_move_pct"),
  estimatedCostPct: real("estimated_cost_pct"),
  netMovePct: real("net_move_pct"),
  mfePct: real("mfe_pct"),
  maePct: real("mae_pct"),
  brierScore: real("brier_score"),
  notified: integer("notified", { mode: "boolean" }).notNull().default(false),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  index("alert_events_symbol_time_idx").on(table.symbol, table.observedAt),
  index("alert_events_state_time_idx").on(table.state, table.observedAt),
  index("alert_events_outcome_idx").on(table.outcomeState, table.observedAt),
]);

export const tradeCases = sqliteTable("trade_cases", {
  id: text("id").primaryKey(),
  activeKey: text("active_key").unique(),
  symbol: text("symbol").notNull(),
  status: text("status", { enum: ["holding", "closed", "archived"] }).notNull().default("holding"),
  side: text("side", { enum: ["LONG", "SHORT"] }).notNull(),
  confidence: integer("confidence").notNull(),
  posteriorLong: real("posterior_long"),
  dataQuality: real("data_quality").notNull(),
  regime: text("regime").notNull(),
  entryDirectionalScore: real("entry_directional_score").notNull(),
  entryAt: integer("entry_at").notNull(),
  entryPrice: real("entry_price").notNull(),
  entryLow: real("entry_low").notNull(),
  entryHigh: real("entry_high").notNull(),
  entryTrigger: text("entry_trigger").notNull(),
  entryThesis: text("entry_thesis").notNull(),
  entryChecksJson: text("entry_checks_json").notNull().default("[]"),
  exitRulesJson: text("exit_rules_json").notNull().default("[]"),
  entryEvidenceJson: text("entry_evidence_json").notNull().default("[]"),
  entryCounterEvidenceJson: text("entry_counter_evidence_json").notNull().default("[]"),
  entryMetricsJson: text("entry_metrics_json").notNull().default("[]"),
  entrySnapshotJson: text("entry_snapshot_json").notNull().default("{}"),
  initialStopPrice: real("initial_stop_price").notNull(),
  currentStopPrice: real("current_stop_price").notNull(),
  takeProfit1Price: real("take_profit_1_price").notNull(),
  takeProfit2Price: real("take_profit_2_price").notNull(),
  target1HitAt: integer("target_1_hit_at"),
  maxHoldingMinutes: integer("max_holding_minutes").notNull(),
  plannedRiskPct: real("planned_risk_pct").notNull(),
  riskReward: real("risk_reward").notNull(),
  riskBudgetUsdt: real("risk_budget_usdt").notNull(),
  suggestedNotionalUsdt: real("suggested_notional_usdt").notNull(),
  contractType: text("contract_type").notNull().default("USDT_PERPETUAL"),
  marginMode: text("margin_mode").notNull().default("isolated"),
  leverage: integer("leverage").notNull().default(1),
  leverageReason: text("leverage_reason").notNull().default("旧模型未记录自适应杠杆"),
  marginUsdt: real("margin_usdt").notNull().default(0),
  contractNotionalUsdt: real("contract_notional_usdt").notNull().default(0),
  quantity: real("quantity").notNull().default(0),
  estimatedLiquidationPrice: real("estimated_liquidation_price"),
  simulationModel: text("simulation_model").notNull().default("contract_v2"),
  accountBalanceBeforeUsdt: real("account_balance_before_usdt").notNull().default(1000),
  accountBalanceAfterUsdt: real("account_balance_after_usdt"),
  lastPrice: real("last_price").notNull(),
  lastEvaluatedAt: integer("last_evaluated_at").notNull(),
  maxPriceSeen: real("max_price_seen").notNull(),
  minPriceSeen: real("min_price_seen").notNull(),
  adverseFlowCount: integer("adverse_flow_count").notNull().default(0),
  unrealizedGrossPct: real("unrealized_gross_pct").notNull().default(0),
  unrealizedNetPct: real("unrealized_net_pct").notNull().default(0),
  unrealizedGrossUsdt: real("unrealized_gross_usdt").notNull().default(0),
  unrealizedNetUsdt: real("unrealized_net_usdt").notNull().default(0),
  progressR: real("progress_r").notNull().default(0),
  exitAt: integer("exit_at"),
  exitPrice: real("exit_price"),
  exitCode: text("exit_code", { enum: ["take_profit", "stop_loss", "breakeven", "structure_reversal", "flow_reversal", "macro_risk", "timeout"] }),
  exitReason: text("exit_reason"),
  exitEvidenceJson: text("exit_evidence_json").notNull().default("[]"),
  exitMetricsJson: text("exit_metrics_json").notNull().default("[]"),
  grossMovePct: real("gross_move_pct"),
  estimatedCostPct: real("estimated_cost_pct"),
  netMovePct: real("net_move_pct"),
  grossPnlUsdt: real("gross_pnl_usdt"),
  estimatedCostUsdt: real("estimated_cost_usdt"),
  netPnlUsdt: real("net_pnl_usdt"),
  mfePct: real("mfe_pct"),
  maePct: real("mae_pct"),
  holdMinutes: real("hold_minutes"),
  lessonJson: text("lesson_json").notNull().default("{}"),
  learningApplied: integer("learning_applied", { mode: "boolean" }).notNull().default(false),
  entryNotified: integer("entry_notified", { mode: "boolean" }).notNull().default(false),
  target1Notified: integer("target_1_notified", { mode: "boolean" }).notNull().default(false),
  exitNotified: integer("exit_notified", { mode: "boolean" }).notNull().default(false),
  archivedAt: integer("archived_at"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  index("trade_cases_symbol_entry_idx").on(table.symbol, table.entryAt),
  index("trade_cases_status_entry_idx").on(table.status, table.entryAt),
  index("trade_cases_exit_idx").on(table.exitAt),
]);

export const symbolLifecycle = sqliteTable("symbol_lifecycle", {
  symbol: text("symbol").primaryKey(),
  state: text("state", { enum: ["observing", "pre_alert", "blocked", "holding", "cooldown"] }).notNull(),
  side: text("side", { enum: ["LONG", "SHORT", "WAIT"] }).notNull(),
  activeTradeId: text("active_trade_id"),
  cooldownUntil: integer("cooldown_until"),
  lastTransitionAt: integer("last_transition_at").notNull(),
  lastObservedAt: integer("last_observed_at").notNull(),
  decisionJson: text("decision_json").notNull().default("{}"),
});

export const strategyMemory = sqliteTable("strategy_memory", {
  id: text("id").primaryKey(),
  symbol: text("symbol").notNull(),
  side: text("side", { enum: ["LONG", "SHORT"] }).notNull(),
  sampleCount: integer("sample_count").notNull().default(0),
  wins: integer("wins").notNull().default(0),
  losses: integer("losses").notNull().default(0),
  bayesAlpha: real("bayes_alpha").notNull().default(1),
  bayesBeta: real("bayes_beta").notNull().default(1),
  averageNetPct: real("average_net_pct").notNull().default(0),
  averageMfePct: real("average_mfe_pct").notNull().default(0),
  averageMaePct: real("average_mae_pct").notNull().default(0),
  grossProfitSumPct: real("gross_profit_sum_pct").notNull().default(0),
  grossLossSumPct: real("gross_loss_sum_pct").notNull().default(0),
  targetExits: integer("target_exits").notNull().default(0),
  stopExits: integer("stop_exits").notNull().default(0),
  reversalExits: integer("reversal_exits").notNull().default(0),
  timeoutExits: integer("timeout_exits").notNull().default(0),
  regimeBreakdownJson: text("regime_breakdown_json").notNull().default("{}"),
  lastLessonJson: text("last_lesson_json").notNull().default("{}"),
  lastAppliedTradeId: text("last_applied_trade_id"),
  updatedAt: integer("updated_at").notNull(),
}, (table) => [
  index("strategy_memory_symbol_side_idx").on(table.symbol, table.side),
]);

export const scanRuns = sqliteTable("scan_runs", {
  id: text("id").primaryKey(),
  startedAt: integer("started_at").notNull(),
  completedAt: integer("completed_at"),
  status: text("status", { enum: ["running", "completed", "degraded", "failed"] }).notNull(),
  universeSize: integer("universe_size").notNull().default(0),
  deepScanned: integer("deep_scanned").notNull().default(0),
  confirmedCount: integer("confirmed_count").notNull().default(0),
  preAlertCount: integer("pre_alert_count").notNull().default(0),
  averageDataQuality: real("average_data_quality"),
  durationMs: integer("duration_ms"),
  error: text("error"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [index("scan_runs_started_idx").on(table.startedAt)]);

export const appSettings = sqliteTable("app_settings", {
  id: integer("id").primaryKey().default(1),
  alertStyle: text("alert_style", { enum: ["early", "balanced", "confirmed"] }).notNull().default("balanced"),
  universeLimit: integer("universe_limit").notNull().default(30),
  deepScanLimit: integer("deep_scan_limit").notNull().default(8),
  minConfidence: integer("min_confidence").notNull().default(72),
  coreSymbolsJson: text("core_symbols_json").notNull().default('["BTC_USDT","ETH_USDT","SOL_USDT","HYPE_USDT"]'),
  roundTripCostBps: real("round_trip_cost_bps").notNull().default(8),
  trialCapitalUsdt: real("trial_capital_usdt").notNull().default(1000),
  maxRiskPerAlertUsdt: real("max_risk_per_alert_usdt").notNull().default(10),
  dailyPauseUsdt: real("daily_pause_usdt").notNull().default(30),
  maxDrawdownUsdt: real("max_drawdown_usdt").notNull().default(100),
  scanEnabled: integer("scan_enabled", { mode: "boolean" }).notNull().default(true),
  pushEnabled: integer("push_enabled", { mode: "boolean" }).notNull().default(false),
  updatedAt: integer("updated_at").notNull(),
});

export const pushSubscriptions = sqliteTable("push_subscriptions", {
  id: text("id").primaryKey(),
  accountId: text("account_id"),
  endpoint: text("endpoint").notNull().unique(),
  p256dh: text("p256dh").notNull(),
  auth: text("auth").notNull(),
  userAgent: text("user_agent"),
  createdAt: integer("created_at").notNull(),
  lastSuccessAt: integer("last_success_at"),
  failureCount: integer("failure_count").notNull().default(0),
  disabledAt: integer("disabled_at"),
}, (table) => [
  index("push_subscriptions_active_idx").on(table.disabledAt),
  index("push_subscriptions_account_idx").on(table.accountId, table.disabledAt),
]);

export const regimeState = sqliteTable("regime_state", {
  symbol: text("symbol").primaryKey(),
  posteriorLong: real("posterior_long").notNull().default(0.5),
  regime: text("regime").notNull().default("unknown"),
  lastScore: real("last_score").notNull().default(0),
  updatedAt: integer("updated_at").notNull(),
});
